

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

schema_search_path: :test

development:
  <<: *default
  database: fashionize_development

  
test:
  <<: *default
  database: fashionize_test

production:
  <<: *default
  database: fashionize_production
  username: fashionize
  password: <%= ENV['FASHIONIZE_DATABASE_PASSWORD'] %>
