# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26f2f0bcbe8ad8cdb3438bff4ff2be1aa5d0901af8ff20d82079c7bf054d29d36e03e2f5d12848a0c8758765dc7b572118c800bafe68333f7e552e5abdaa9296

test:
  secret_key_base: c99e20ec5a4a747f0568f5b876e56f3d633ff594122e3295bc47be0e35077314ab8476b95392b74a3eeff28746facf36bcdd4d8af0c2cfede3bb0256e7d8f764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
